
name : Tests

on:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@v2
    - name: multi lines payload
      run: |
        echo 'PAYLOAD<<EOF'
        curl -s https://catfact.ninja/fact | jq -r '.fact' 
        curl -s https://catfact.ninja/fact | jq -r '.fact' 
        echo EOF
        >> "$GITHUB_ENV"
    - name: log
      run: |
        echo $PAYLOAD
        echo ------
        echo ${{ env.PAYLOAD }}
        echo ------
        echo $${{ toJSON(env.PAYLOAD) }}
