
name : Tests

on:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@v2
    - name: log
      run: ls
    - name: change directory
      working-directory: folder1
      run: ls && cat file.txt
    - name: cd
      run: cd folder2
