
name : Tests

on:
  workflow_dispatch:
  
jobs:
  build_array_job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.build_array.outputs.array }}
    steps:
      - uses: actions/checkout@v2
      - id: build_array
        run: |-
          array=( $(git show --name-only --oneline | grep folder |cut -d/ -f1 | uniq) )
          echo $array
          echo "array=$array" >> "$GITHUB_OUTPUT"

  matrix_job:
    runs-on: ubuntu-latest
    needs: build_array_job
    steps:
      - env:
          RESULT: ${{needs.build_array_job.outputs.result}}
        run: echo "$RESULT"




