
name : Tests

on:
  workflow_dispatch:
  
jobs:
  build_array_job:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build_array.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - id: build_array
        shell: bash
        run: |-
          chmod +X getarray.sh
          ARRAY=$(./getarray.sh)
          echo "result=$(jq -cn --argjson paths "$ARRAY" '{folder: $paths}')" >> $GITHUB_OUTPUT          

  matrix_job:
    runs-on: ubuntu-latest
    needs: build_array_job
    steps:
      - env:
          RESULT: ${{ fromJSON(needs.build_array_job.outputs.matrix) }}
        run: echo "$RESULT"




