
name : Tests

on:
  workflow_dispatch:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@v2
    - name: multi lines payload
      run: |
        echo 'REPORT<<EOF' >> $GITHUB_ENV
         echo "\`\`\`console" >> $GITHUB_ENV
         curl -s https://catfact.ninja/fact | jq -r '.fact' >> $GITHUB_ENV
         echo "\`\`\`" >> $GITHUB_ENV
         echo 'EOF' >> $GITHUB_ENV
    - name: log
      run: |
        echo $REPORT
        echo ------
        echo ${{ env.REPORT }}
        echo ------
        echo $${{ toJSON(env.REPORT) }}
