
name : Tests

on:
  workflow_dispatch:
  
jobs:
  first:
    outputs:
      output_test: ${{ steps.build_array.outputs.TEST }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build_array
      id: build_array
      run: |-
        array=( $(git show --name-only --oneline | grep folder |cut -d/ -f1 | uniq) )
        echo $array
        echo "TEST=1233444" >> "$GITHUB_OUTPUT"

  second:
    runs-on: ubuntu-latest
    steps:
      - run: |-
         echo "${{ needs.first.outputs.ARRAY }}"
         echo '-------'
          echo "${{ needs.first.outputs.output_test }}"




