
name : Tests

on:
  workflow_dispatch:
  
jobs:
  build_array_job:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build_array.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - id: build_array
        shell: bash
        run: |-
          mapfile
          chmod +x getarray.sh
          ARRAY=$(./getarray.sh)
          echo "result=$(jq -cn --argjson paths "$ARRAY" '{folder: $paths}')" >> $GITHUB_OUTPUT          


  run-matrix:
    needs: build_array_job
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build_array_job.outputs.matrix) }}
    steps:
      - run: echo ${{matrix.folder}}




