
name : Tests

on:
  workflow_dispatch:
  
jobs:
  build_array_job:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build_array.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - id: build_array
        shell: bash
        env:
          REF: ${{ github.ref }}
          SHA: ${{ github.sha }}
        run: |-
          echo "$REF"
          echo ------
          echo "$SHA"


#  run-matrix:
#    needs: build_array_job
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{ fromJson(needs.build_array_job.outputs.matrix) }}
#    steps:
#      - run: echo ${{matrix.folder}}




